services:
  postgres:
    image: postgres:15-alpine
    platform: linux/amd64
    container_name: postgresDB
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=ariusDB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U health"]
      interval: 30s
      timeout: 5s
      retries: 5
    networks:
      - db

  email_service:
    build:
      context: ./email_service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    networks:
      - backend

  app-server:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - app-server
    environment:
      BACKEND_URL: "http://app-server:5000"
      SECRET_KEY: "well-shucks"
    networks:
      - backend

networks:
  backend:
    driver: bridge
  db:
    driver: bridge
