# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - DominacjaGenetyczna

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_e769479ea00543528649efe4e48abbd4 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2b8e3beb604443b68778133dda1f1caf }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/dominacjagenetyczna/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'DominacjaGenetyczna'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_67da5b7a16cc486ca821a6581b2a64e6 }}
        images: 'mcr.microsoft.com/dominacjagenetyczna/appsvc/staticsite:${{ github.sha }}'
