name: Build and deploy container app to Azure Web App - dominacjagenetyczna

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_1787bd2d1eb44675a122e008238ba7c7 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a290cf4dd4f24d05beab508d4563483d }}

    - name: Build and push container image using Docker Compose
      run: |
        docker-compose -f docker-compose.yml build
        docker-compose -f docker-compose.yml push

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dominacjagenetyczna'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b0c191c508d54ab6a5ee0470c1141e45 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_1787bd2d1eb44675a122e008238ba7c7 }}/appsvc/staticsite:${{ github.sha }}'
